# Generated by Django 5.2 on 2025-04-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_projeto", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="usuarios",
            new_name="Usuario",
        ),
    ]
